apiVersion: v1
kind: Service
metadata:
  name: ken-service
  namespace: cypress
spec:
  ports:
    - name: rpc
      protocol: TCP
      port: 80
      targetPort: 8551
    - name: ws
      protocol: TCP
      port: 8552
      targetPort: 8552
  selector:
    app: ken
  type: ClusterIP